package com.iblog.model;

import com.iblog.model.base.BaseCommentReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentReply extends BaseCommentReply<CommentReply> {
	public static final CommentReply dao = new CommentReply();
}
