package com.iblog.model;

import com.iblog.model.base.BaseInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Information extends BaseInformation<Information> {
	public static final Information dao = new Information();
	
	public Information getInformation(){
		Information information = findFirst("select * from information");
	    return information;
	}
}
