package com.iblog.model;

import com.iblog.model.base.BaseMessageReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageReply extends BaseMessageReply<MessageReply> {
	public static final MessageReply dao = new MessageReply();
}
