package com.iblog.model;

import com.iblog.model.base.BaseSite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Site extends BaseSite<Site> {
	public static final Site dao = new Site();
	
	public Site getSite(){
		Site site = findFirst("select * from site");
	    return site;
	}
}
