package com.iblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSite<M extends BaseSite<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setLogtime(java.util.Date logtime) {
		set("logtime", logtime);
	}

	public java.util.Date getLogtime() {
		return get("logtime");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCopyright(java.lang.String copyright) {
		set("copyright", copyright);
	}

	public java.lang.String getCopyright() {
		return get("copyright");
	}

	public void setLicense(java.lang.String license) {
		set("license", license);
	}

	public java.lang.String getLicense() {
		return get("license");
	}

	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}

	public java.lang.String getLogo() {
		return get("logo");
	}

	public void setBanner(java.lang.String banner) {
		set("banner", banner);
	}

	public java.lang.String getBanner() {
		return get("banner");
	}

	public void setBannerTitle(java.lang.String bannerTitle) {
		set("bannerTitle", bannerTitle);
	}

	public java.lang.String getBannerTitle() {
		return get("bannerTitle");
	}

	public void setBannerContent(java.lang.String bannerContent) {
		set("bannerContent", bannerContent);
	}

	public java.lang.String getBannerContent() {
		return get("bannerContent");
	}

	public void setSpiderStatus(java.lang.Integer spiderStatus) {
		set("spiderStatus", spiderStatus);
	}

	public java.lang.Integer getSpiderStatus() {
		return get("spiderStatus");
	}

}
