package com.iblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return get("tags");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("categoryId", categoryId);
	}

	public java.lang.Integer getCategoryId() {
		return get("categoryId");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setTitlePicture(java.lang.String titlePicture) {
		set("titlePicture", titlePicture);
	}

	public java.lang.String getTitlePicture() {
		return get("titlePicture");
	}

	public void setStatement(java.lang.String statement) {
		set("statement", statement);
	}

	public java.lang.String getStatement() {
		return get("statement");
	}

	public void setSourceName(java.lang.String sourceName) {
		set("sourceName", sourceName);
	}

	public java.lang.String getSourceName() {
		return get("sourceName");
	}

	public void setSourceURL(java.lang.String sourceURL) {
		set("sourceURL", sourceURL);
	}

	public java.lang.String getSourceURL() {
		return get("sourceURL");
	}

	public void setLogtime(java.util.Date logtime) {
		set("logtime", logtime);
	}

	public java.util.Date getLogtime() {
		return get("logtime");
	}

	public void setViews(java.lang.Integer views) {
		set("views", views);
	}

	public java.lang.Integer getViews() {
		return get("views");
	}

	public void setComments(java.lang.Integer comments) {
		set("comments", comments);
	}

	public java.lang.Integer getComments() {
		return get("comments");
	}

	public void setVotes(java.lang.Integer votes) {
		set("votes", votes);
	}

	public java.lang.Integer getVotes() {
		return get("votes");
	}

	public void setVisible(java.lang.String visible) {
		set("visible", visible);
	}

	public java.lang.String getVisible() {
		return get("visible");
	}

}
