package com.iblog.config;

import com.iblog.model.Blog;
import com.iblog.model.Category;
import com.iblog.model.Comment;
import com.iblog.model.CommentReply;
import com.iblog.model.Friend;
import com.iblog.model.Information;
import com.iblog.model.Message;
import com.iblog.model.MessageReply;
import com.iblog.model.Site;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("category", "id", Category.class);
		arp.addMapping("comment", "id", Comment.class);
		arp.addMapping("comment_reply", "id", CommentReply.class);
		arp.addMapping("friend", "id", Friend.class);
		arp.addMapping("information", "id", Information.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("message_reply", "id", MessageReply.class);
		arp.addMapping("site", "id", Site.class);
	}
}